services:
  backend:
    build: .
    container_name: reading-companion-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - /www/dk_project/wwwroot/lit.handy.xin/data:/app/instance
      - /www/dk_project/wwwroot/lit.handy.xin/audio_files:/app/audio_files
    environment:
      - FLASK_ENV=production
      - TZ=Asia/Shanghai
    dns:
      - 223.5.5.5
      - 8.8.8.8
